name: API Test Automation

on:
  push:
    branches:
      - master
      - develop
  pull_request:
    branches:
      - master
      - develop

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Cache Maven dependencies
        uses: actions/cache@v3
        with:
          path: ~/.m2
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-maven-

      - name: Run API Tests with Maven
        run: mvn clean test

      # Generate Allure Report
      - name: Generate Allure Report
        run: mvn allure:serve

      # Upload Allure Report using latest version of actions/upload-artifact
      - name: Upload Allure report as artifact
        uses: actions/upload-artifact@v2  # Cập nhật lên v2 hoặc v3 mới nhất
        with:
          name: allure-report
          path: target/allure-results